services:
  database:
    image: "mariadb:11.8.3"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vacairo
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
  mailer:
    container_name: mailer
    image: axllent/mailpit
    ports: [1025, 8025]
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  mariadb:
    driver: local
